// <auto-generated />
using System;
using Anagrafiche.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anagrafiche.Api.Migrations;

[DbContext(typeof(AnagraficheDbContext))]
partial class AnagraficheDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Anagrafiche.Repository.Model.Recapito", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Cap")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("IdSoggetto")
                    .HasColumnType("int");

                b.Property<string>("Indirizzo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Localita")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NumeroCivico")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Provincia")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TipoIndirizzo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("IdSoggetto");

                b.ToTable("Recapiti");
            });

        modelBuilder.Entity("Anagrafiche.Repository.Model.Soggetto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("CodiceFiscale")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Cognome")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DataDiNascita")
                    .HasColumnType("datetime2");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Soggetti");
            });

        modelBuilder.Entity("Anagrafiche.Repository.Model.Recapito", b =>
            {
                b.HasOne("Anagrafiche.Repository.Model.Soggetto", "Soggetto")
                    .WithMany("ListaRecapiti")
                    .HasForeignKey("IdSoggetto")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Soggetto");
            });

        modelBuilder.Entity("Anagrafiche.Repository.Model.Soggetto", b =>
            {
                b.Navigation("ListaRecapiti");
            });
#pragma warning restore 612, 618
    }
}
